# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-14 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('0', 'Texto'), ('1', 'Si/No'), ('2', 'Eleccion'), ('3', 'Numero')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AtributoAPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Atributo')),
            ],
        ),
        migrations.CreateModel(
            name='JuntaComunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=15)),
                ('encargado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('0', 'Inactivo'), ('1', 'Activo'), ('2', 'Suspendido')], max_length=1)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=15)),
                ('nacimiento', models.DateField()),
                ('telefono_celular', models.CharField(max_length=15)),
                ('telefono_casa', models.CharField(max_length=15)),
                ('domicilio', models.CharField(max_length=400)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('0', 'Soltero/a'), ('1', 'Comprometido/a'), ('2', 'En Relacion ( mas de 1 Anio de noviazgo)'), ('3', 'Casado/a'), ('4', 'Union libre'), ('5', 'Separado/a'), ('6', 'Divorciado/a'), ('7', 'Viudo/a'), ('8', 'Noviazgo(periodo inferior a 1 anio de relacion amorosa)')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='atributoapersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.Persona'),
        ),
    ]
